[package]
name = "plotlib"
version = "0.2.0"
authors = ["Matt Williams <matt@milliams.com>"]
description = "Plotting data structures and tools"
license = "MIT"
repository = "https://github.com/milliams/plotlib"
categories = ["visualization"]

[dependencies]
svg = "0.5.10"
